version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: escaping-network-simplex-server_smp-server_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"

  smp-server:
    image: escaping/smp-server:v6.3.1@sha256:4479ca706e9e9b8ee9b0664555ec81507576ff0092443429611a8cf62f4614f0
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      ADDR: ${DEVICE_HOSTNAME}
      PASS: ${APP_PASSWORD}
    ports:
      - 5223:5223
    volumes:
      - ${APP_DATA_DIR}/data/smp/config:/etc/opt/simplex:z
      - ${APP_DATA_DIR}/data/smp/logs:/var/opt/simplex:z
  xftp-server:
    image: escaping/xftp-server:v6.3.1@sha256:f821d6868c0367650577dc7f126922c079c302fb246416c555cd16caaaf81d26
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      ADDR: ${DEVICE_HOSTNAME}
      QUOTA: "2GB"
    ports:
      - 5443:443
    volumes:
      - ${APP_DATA_DIR}/data/xftp/config:/etc/opt/simplex-xftp:z
      - ${APP_DATA_DIR}/data/xftp/logs:/var/opt/simplex-xftp:z
      - ${APP_DATA_DIR}/data/xftp/files:/srv/xftp:z
