version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: escaping-network-simplex-server_smp-server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  smp-server:
    image: escaping/smp-server:v6.2.0@sha256:9e47e381e75fa84a45aa2a0ccf37ceb00f5dc0d06ff2acb438b4d74fb0a780be
    restart: on-failure
    stop_grace_period: 1m
    environment:
      ADDR: umbrel.local
      PASS: ${APP_PASSWORD}
    ports:
      - 5223:5223
    volumes:
      - ${APP_DATA_DIR}/data/smp/config:/etc/opt/simplex:z
      - ${APP_DATA_DIR}/data/smp/logs:/var/opt/simplex:z
  xftp-server:
    image: escaping/xftp-server:v6.2.0@sha256:00cfb9b40a85d95754ee097665c8dca57ac90a33a1debcafcc747a913e476092
    restart: on-failure
    stop_grace_period: 1m
    environment:
      ADDR: umbrel.local
      QUOTA: "2GB"
    ports:
      - 5443:443
    volumes:
      - ${APP_DATA_DIR}/data/xftp/config:/etc/opt/simplex-xftp:z
      - ${APP_DATA_DIR}/data/xftp/logs:/var/opt/simplex-xftp:z
      - ${APP_DATA_DIR}/data/xftp/files:/srv/xftp:z
