services:
  app_proxy:
    environment:
      APP_HOST: escaping-network-wavelog_wavelog-main_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"
  wavelog-db:
    image: mariadb:11.4@sha256:39596f079862334be04f4231664862e55d4febe54309cc62f750f2297de85b06
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: wavelog
      MARIADB_USER: wavelog
      MARIADB_PASSWORD: wavelog
    volumes:
      - wavelog-dbdata:/var/lib/mysql
  wavelog-main:
    depends_on:
      - wavelog-db
    environment:
      CI_ENV: docker
    image: ghcr.io/wavelog/wavelog:2.0.7@sha256:40721405cfbcbbb1e861c1713202f69cb3416b2753ed5cce02e5542235245eb4
    volumes:
      - wavelog-config:/var/www/html/application/config/docker
      - wavelog-uploads:/var/www/html/uploads
      - wavelog-userdata:/var/www/html/userdata
      
volumes:
  wavelog-dbdata:
  wavelog-uploads:
  wavelog-userdata:
  wavelog-config:
